server:
    port: 8081
spring:
    application:
        name: customerService
    datasource:
        url: jdbc:postgresql://localhost:5432/customer
        username: postgres
        password: 9476
    jpa:
        hibernate:
            ddl-auto: validate


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
