create table customer
(
    id_customer integer generated by default as identity,
    phone_number varchar(11) not null,
    bank_account_id integer,
    primary key (id_customer)
);

insert into customer (phone_number, bank_account_id)
values ('89661894542', 1);