create table customer
(
    id_customer     integer generated by default as identity,
    phone_number    text not null,
    bank_account_id integer,
    primary key (id_customer)
);

insert into customer (phone_number, bank_account_id)
values ('+79661894542', 1),
       ('+447463400028', 2);