server:
    port: 8082
spring:
    application:
        name: accountService
    datasource:
        url: jdbc:postgresql://localhost:5432/account
        username: postgres
        password: 9476


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
