server:
    port: 8083
spring:
    application:
        name: depositService
    datasource:
        url: jdbc:postgresql://localhost:5432/deposit
        username: postgres
        password: 9476


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

