create table deposits_types
(
    id_deposits_types   integer generated by default as identity,
    deposits_types_name varchar(28) not null,
    primary key (id_deposits_types)
);

create table types_percent_payment
(
    id_type_percent_payment     integer generated by default as identity,
    type_percent_payment_period varchar(13) not null,
    primary key (id_type_percent_payment)
);

create table deposits
(
    id_deposit                 integer generated by default as identity,
    deposit_account_id         integer        not null,
    deposits_type_id           integer        not null,
    deposit_refill             boolean        not null,
    deposits_amount            numeric(15, 2) not null,
    start_date                 date           not null,
    end_date                   date           not null,
    deposit_rate               decimal(4, 2)  not null,
    type_percent_payment_id    integer        not null,
    percent_payment_account_id integer        not null,
    percent_payment_date       date           not null,
    capitalization             boolean        not null,
    deposit_refund_account_id  integer        not null,
    primary key (id_deposit),
    foreign key (deposits_type_id) references deposits_types (id_deposits_types),
    foreign key (type_percent_payment_id) references types_percent_payment (id_type_percent_payment)
);

create table request_statuses
(
    id_request_status   integer generated by default as identity,
    request_status_name varchar(21) not null,
    primary key (id_request_status)
);

create table requests
(
    id_request   integer generated by default as identity,
    customer_id  integer not null,
    request_date date    not null,
    deposits_id  integer not null,
    primary key (id_request),
    foreign key (deposits_id) references deposits (id_deposit)
);

create table current_request_status
(
    request_id        integer     not null,
    request_status_id integer     not null,
    change_datetime   timestamptz not null,
    primary key (request_id, request_status_id),
    foreign key (request_id) references requests (id_request),
    foreign key (request_status_id) references request_statuses (id_request_status)
);
